### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Rob117** [ConcurrenyLabs/lambda-env-config#1]
If at all convenient, please specify under what license the code may be used.

Thank you.

**Comment by concurrencylabs** [comment]
This repo is under MIT License. Sorry I forgot to include a LICENSE file, which I have added now. You're welcome to use the code as you see fit, but since AWS has announced the new [Environment Variables](http://docs.aws.amazon.com/lambda/latest/dg/env_variables.html) feature, I recommend using that feature instead.

**Comment by Rob117** [comment]
Thank you very much!

I was using environment variables, but it turns out that your code is still super useful. I have 5 lambdas across 3 stages with things like encryption passwords and database names that need to be shared amongst them (divided by stage). If the password for test changed, I would have to remember to change it in all five lambdas or my project would completely break. This solves that problem elegantly.
